# Generated by Django 4.0.1 on 2022-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('tryMe', models.CharField(max_length=500)),
                ('auth', models.CharField(max_length=10)),
                ('working', models.BooleanField(default=True)),
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
